//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAN_data_logger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAN_data_logger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ammeter {
            get {
                object obj = ResourceManager.GetObject("ammeter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bluetooth {
            get {
                object obj = ResourceManager.GetObject("bluetooth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO_ 1536 DevMsg1: 8 _DiagCalTool
        /// SG_ DevVal_8bit : 56|8@1+ (1,0) [0|255] &quot;&quot; Vector__XXX
        /// SG_ DevVal_4bit : 48|4@1+ (1,0) [0|15] &quot;&quot; Vector__XXX
        /// SG_ DevFlag4 : 55|1@1+ (1,0) [0|1] &quot;&quot; Vector__XXX
        /// SG_ DevFlag3 : 54|1@1+ (1,0) [0|1] &quot;&quot; Vector__XXX
        /// SG_ DevFlag2 : 53|1@1+ (1,0) [0|1] &quot;&quot; Vector__XXX
        /// SG_ DevFlag1 : 52|1@1+ (1,0) [0|1] &quot;&quot; Vector__XXX
        /// SG_ DevStorageModeReq : 0|1@1+ (1,0) [0|1] &quot;0&quot;  Bms
        /// SG_ DevStorageCfgOrTime : 16|16@1+ (1,0) [5|65535] &quot;ms&quot;  Bms
        /// SG_ DevStorageCfgOrEN : 8|1@1+ (1,0) [0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CANdbcFile {
            get {
                return ResourceManager.GetString("CANdbcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disconnected {
            get {
                object obj = ResourceManager.GetObject("disconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage{
        ///	-BMS:(1937,37)
        ///	-Cell{n}r[1,16]:(1972 + Floor(1.0 * (n-1)/4), 3 - (n-1)%4)
        ///}
        ///Current{
        ///	-BMS:(1937,38)
        ///}
        ///Temperature{
        ///	-Heatsink{n}r[1,4]:(1979,4-n)
        ///	-Cell Pair{n}l[9,7,1]:(1977,2+i)
        ///	-Cell Pair{n}l[11,13,15,5,3]:(1976,i)
        ///}
        ///State{
        ///	-Charge (SoC):(1939,28)
        ///	-Health (SoH):(1939,29)
        ///}
        ///Cycle Count{
        ///	-:(1945,0)
        ///}.
        /// </summary>
        internal static string EssentialParameters {
            get {
                return ResourceManager.GetString("EssentialParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontsFree_Net_Kardust_Bold {
            get {
                object obj = ResourceManager.GetObject("FontsFree_Net_Kardust_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forsetiPack {
            get {
                object obj = ResourceManager.GetObject("forsetiPack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap multimeter {
            get {
                object obj = ResourceManager.GetObject("multimeter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NyoLogo {
            get {
                object obj = ResourceManager.GetObject("NyoLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NyoLogoBg {
            get {
                object obj = ResourceManager.GetObject("NyoLogoBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7B7 8 10 09 10 09 13 09 16 09 :77363490
        ///7B2 8 13 01 00 00 00 00 00 00 :77369736
        ///7B3 8 DB 80 F0 E0 FE 03 00 00 :77373292
        ///791 8 15 91 2A A1 17 00 00 00 :77379538
        ///7B5 8 12 09 10 09 12 09 13 09 :77383095
        ///792 8 0D 69 91 01 65 D2 26 94 :77389341
        ///794 8 22 91 12 09 91 10 39 91 :77392898
        ///791 8 15 91 2A A1 27 00 05 00 :77399144
        ///7B2 8 13 01 00 00 00 00 00 00 :77402701
        ///7B3 8 DB 80 F0 E0 FE 03 00 00 :77406257
        ///794 8 63 91 00 00 00 00 00 00 :77415193
        ///7B2 8 13 01 00 00 00 00 00 00 :77418749
        ///7B3 8 DB 80 F0 E0 FE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sampleData {
            get {
                return ResourceManager.GetString("sampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SoHLogo {
            get {
                object obj = ResourceManager.GetObject("SoHLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SoHLogoBg {
            get {
                object obj = ResourceManager.GetObject("SoHLogoBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap textFileImage {
            get {
                object obj = ResourceManager.GetObject("textFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thermometer {
            get {
                object obj = ResourceManager.GetObject("thermometer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap USB {
            get {
                object obj = ResourceManager.GetObject("USB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
